Small Fixes.
tkinter comes default. Resolved this issues by removing from requirements.txt

(.venv) PS C:\Users\***\Documents\GitHub\Rares-Apkm-to-APK-GUI> pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)

Added .venv/ to .gitignore.